Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  
  config.vm.provider "vmware_desktop" do |v|
    v.gui = true
    v.linked_clone = true
  end

  config.vm.hostname = "VM1firewall"
  # Interface vers le réseau WEB (LAN 1)
  config.vm.network "private_network", ip: "192.168.100.1"
  # Interface vers le réseau DB (LAN 2)
  config.vm.network "private_network", ip: "192.168.10.1"

  config.vm.provision "shell", inline: "sysctl -w net.ipv4.ip_forward=1"
  config.vm.provision "shell", inline: <<-SHELL
    # Activation du routage IP
    echo 1 | sudo tee /proc/sys/net/ipv4/ip_forward

    # Nettoyage des tables
    sudo iptables -F
    sudo iptables -X
    sudo iptables -t nat -F

    # --- TABLE NAT (Redirection et Sortie) ---
    # Rediriger le trafic du port 80 (Public) vers la VM2 (Web)
    sudo iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j DNAT --to-destination 192.168.100.10:80
    # Masquage d'IP pour permettre aux autres VMs d'aller sur le Web
    sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE

    # --- TABLE FILTER (Sécurité) ---
    # Autoriser l'accès au serveur Web (Port 80)
    sudo iptables -A FORWARD -i eth0 -o eth1 -p tcp --dport 80 -d 192.168.100.10 -j ACCEPT
    # Autoriser le retour des paquets (Stateful)
    sudo iptables -A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
    
    #Autoriser l'utilisateur d'avoir une connexion au serveur et interdir tout autre trafic 
    #du web vers la base de donnees pour plus de securite
    sudo iptables -A FORWARD -i eth1 -o eth2 -p tcp --dport 3306 -j ACCEPT
    sudo iptables -A FORWARD -i eth2 -o eth1 -m state --state ESTABLISHED,RELATED -j ACCEPT
    sudo iptables -A FORWARD -i eth1 -o eth2 -j DROP
  SHELL

end